### ISSUE TITLE
Suggestion: Add a config option to disable in specific worlds

### ISSUE THREAD

**Issue by itsChix** [evancolewright/HeadDrops#1]
Hey there!

I'm running a Survival and a BedWars gamemode on one server through Multiverse. However, when a player kills someone in the bedwars world, his head drops and I don't want that since on BedWars you can respawn infinitely and the map is pretty small. Please add a config option to make player heads not drop in certain worlds.

Thanks!

**Comment by evancolewright** [comment]
Added in v1.5 and forgot to reference it in my commit.
