### ISSUE TITLE
Only operators can obtain heads

### ISSUE THREAD

**Issue by 4untochrist** [evancolewright/HeadDrops#12]
### Plugin Version
 
1.5.6

### Server Version

1.18.2 Paper

### StackTrace

N/A

### Steps to Reproduce

Kill a non oped player as a regular player. no permission for regular players to obtain heads.

**Comment by evancolewright** [comment]
Thanks for reporting an issue. 

Players don't need permission to get head drops from other players.  It's also worth noting that players don't _**always**_ drop their heads unless the configuration chance is set to 1.0 (which is not the default).  Please post your config file.

**Comment by 4untochrist** [comment]
# ============================================================================= #
#                                                                               #
#                                                                               #
#   ██╗  ██╗███████╗ █████╗ ██████╗ ██████╗ ██████╗  ██████╗ ██████╗ ███████╗   #
#   ██║  ██║██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔═══██╗██╔══██╗██╔════╝   #
#   ███████║█████╗  ███████║██║  ██║██║  ██║██████╔╝██║   ██║██████╔╝███████╗   #
#   ██╔══██║██╔══╝  ██╔══██║██║  ██║██║  ██║██╔══██╗██║   ██║██╔═══╝ ╚════██║   #
#   ██║  ██║███████╗██║  ██║██████╔╝██████╔╝██║  ██║╚██████╔╝██║     ███████║   #
#   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚══════╝   #
#                                                                               #
#                                                                               #
#           Source Code: https://github.com/evancolewright/HeadDrops            #
#        Bug Reports: https://github.com/evancolewright/HeadDrops/issues        #
#                                                                               #
#                               VERSION 1.5.6                                   #
# ============================================================================= #


# If enabled, the head of a slain player will be added to the killer's inventory rather than dropping on the ground
transport_to_killer_inventory: true

# Configuration section for normal head drops (when a player dies of natural causes)
# Available placeholders:
# {PLAYER} - The player's name
# {TIMESTAMP} - The formatted time that the player died.
# Make sure all timestamps are fully uppercase!
normal:
  enabled: true
  disabled_worlds:
    - "disabledworld1"
    - "disabledworld2"
  drop_chance: 0.75
  head:
    name: "&a&l{PLAYER}'s &7&lHead"
    lore:
      - "&eDied on&7: &a&l{TIMESTAMP}"

# Configuration section for slain head drops (when a player is slain by another player)
# Available placeholders:
# {PLAYER} - The player's name
# {KILLER} - The person who killed the player
# {MURDER_WEAPON} - The name of the item that was used to kill the player.
# {TIMESTAMP} - The formatted time that the player was killed.
# Make sure all timestamps are fully uppercase!
slain:
  enabled: true
  disabled_worlds:
    - "disabledworld1"
    - "disabledworld2"
  drop_chance: 100.0
  head:
    name: "&a&l{PLAYER}'s &7&lHead"
    lore:
      - "&eDied on&7: &f&l{TIMESTAMP}"
      - "&eKilled by: &f&l{KILLER}"
      - "&eKilled with: &f&l{MURDER_WEAPON}"

**Comment by 4untochrist** [comment]
ah i see hat you mean with the drop_chance, it was a issue on my behalf.

**Comment by evancolewright** [comment]
> ah i see hat you mean with the drop_chance, it was a issue on my behalf.

So it's working now?
