### ISSUE TITLE
Nothing drops

### ISSUE THREAD

**Issue by Hendrik717** [evancolewright/HeadDrops#18]
### Plugin Version
 1.5.6

### Server Version
18.2

### StackTrace
N/A

### Steps to Reproduce

When I killed a player I didn't get a head

**Comment by evancolewright** [comment]
Have you set the chances in the config?

**Comment by Hendrik717** [comment]
Yes I changed it to 100 because I want from every Seth a head

**Comment by Hendrik717** [comment]
What’s the highest rate I can Setup

**Comment by evancolewright** [comment]
> What’s the highest rate I can Setup

You should set it to 1 if you want heads to always drop.  Also, make sure that whoever you are killing is not an operator.  Operators do not drop heads.

If heads still do not drop, look in console for an error and paste that here.

**Comment by evancolewright** [comment]
Closed.  Reopen if the issue is still present.
