### ISSUE TITLE
LORE of head

### ISSUE THREAD

**Issue by Teykingo** [evancolewright/HeadDrops#4]
Hello, when I want to change the color of the head there is no change all the time the same, I restart the server but still nothing changes
why?

![image](https://user-images.githubusercontent.com/96445458/154918382-514cf6de-6b93-4330-be47-9528cd77008d.png)
![image](https://user-images.githubusercontent.com/96445458/154918441-a00afde2-a149-4c30-9125-9f41a0dc2075.png)

**Comment by evancolewright** [comment]
Hey, thanks for reporting an issue.  I apologize for the late response.

Are you sure that you are saving the file?  If so, **what version is your server running** and **are you getting any errors in your console**?

**Comment by evancolewright** [comment]
Closed due to inactivity.  Feel free to re-open if you are still experiencing issues.
